name: Checking for 'mashed' JS
run-name: Checking for 'mashed' JS

on: [push]

jobs:
  Test-Insecure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        working-directory: mashup
        run: npm install
      - name: Lint
        working-directory: mashup
        run: npm run lint index.js
